name: Build and package

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

  schedule:
    - cron: "19 3 * * *" # everyday at 03:19

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merged.sha }}

      - name: Import signing certificate into keychain
        run: |
          KEYCHAIN_FILE=default.keychain
          KEYCHAIN_PASSWORD=myvoiceismypassport
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_FILE
          security default-keychain -s $KEYCHAIN_FILE
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_FILE
          security import <(echo $SIGNING_CERTIFICATE_P12_DATA | base64 --decode) \
                          -f pkcs12 \
                          -k $KEYCHAIN_FILE \
                          -P $SIGNING_CERTIFICATE_PASSWORD \
                          -T /usr/bin/codesign \
                          -T /usr/bin/security
          security set-key-partition-list \
                   -S apple-tool:,apple: \
                   -s -k $KEYCHAIN_PASSWORD $KEYCHAIN_FILE
          security find-identity -v
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          git clone https://github.com/beeware/briefcase
          cd briefcase
          git apply ../patches/briefcase.patch
          cd ..
          python3 -m pip install --upgrade ./briefcase
          chmod +x ./scripts/post-build-macos.sh

      - name: Build app
        id: build
        run: |
          briefcase build
          ./scripts/post-build-macos.sh
          DMG_PATH=$( briefcase package | grep "Packaged" | cut -d' ' -f 3)

          echo "dmg created: $DMG_PATH"
          echo "::set-output name=dmg_path::${DMG_PATH}"

      - name: Notarize app
        run: |
          echo "${{ steps.dmg.outputs.dmg_name }}"
          npx notarize-cli --bundle-id "com.samschott.maestral" \
                           --file ${{ steps.build.outputs.dmg_path }}
        env:
          NOTARIZE_USERNAME: ${{ secrets.NOTARIZE_USERNAME }}
          NOTARIZE_PASSWORD: ${{ secrets.NOTARIZE_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dmg
          path: ${{ steps.build.outputs.dmg_path }}
