name: Lint

on: [push, pull_request]

jobs:
  checks:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install
      run: |
        python -m pip install -U pip
        python -m pip install -U .[dev]
    - name: black
      run: black . --check --diff
    - name: flake8
      run: flake8 .
    - name: mypy
      run: mypy
